Repository Varkaria/guweb, pull requests merged in 2021-07, with the labels that each got.

#2 (Recommit) Half working admin panel
  blueprints/admin.py
  static/css/pages/admin/style.css
  templates/admin/base.html
  templates/admin/beatmaps.html
  templates/admin/log.html
  templates/admin/users.html
Labels: size/XL

#4 synchronize nginx tweaks
  ext/nginx.conf
Labels: size/M

#6 corn
  main.py
Labels: bug, size/XS, type:framework

#9 redirect for osu change avatar button
  blueprints/frontend.py
Labels: size/XS

#8 Merge branch 'main' into development
  SECURITY.md
  ext/nginx.conf
  main.py
Labels: size/M

#10 fix .gitignore
  .gitignore
Labels: size/XS

#13 fix regex
  ext/nginx.conf
Labels: size/XS

#11 Update Guweb version to 1.3.0
  .data/backgrounds/.gitkeep
  .data/banners/.gitkeep
  .gitignore
  blueprints/api.py
  blueprints/frontend.py
  ext/nginx.conf
  ext/requirements.txt
  main.py
  objects/utils.py
  static/css/pages/auth.css
  static/css/pages/home.css
  static/css/pages/leaderboard.css
  static/css/pages/profile.css
  static/css/pages/settings/style.css
  static/css/pages/verify.css
  static/css/style.css
  static/js/asserts/vue-flags.js
  static/js/pages/leaderboard.js
  static/js/pages/profile.js
  templates/404.html
  templates/admin/base.html
  templates/admin/home.html
  templates/base.html
  templates/components/navbar.html
  templates/leaderboard.html
  templates/profile.html
  templates/settings/avatar.html
  templates/settings/base.html
  templates/settings/custom.html
  templates/settings/password.html
  templates/settings/profile.html
  templates/settings/sidebar.html
  templates/verify.html
Labels: enhancement, size/XXL, type:frontend
